import { getDisplayName, getOptions } from '../../../common/_internal';
import { UnitMetadata } from '../../_shared/types';
import { ForceDiagram } from './forceDiagrams';

export enum Unit {
  LB101 = 'LB101',
  LB104 = 'LB104',
  LB107 = 'LB107',
  LB110 = 'LB110',
  LB123 = 'LB123',
  LB125 = 'LB125',
  LB132 = 'LB132',
  LB136 = 'LB136',
  LB140 = 'LB140',
  LB146 = 'LB146',
  LB148 = 'LB148',
  LB150 = 'LB150',
  LB152 = 'LB152',
  LB155 = 'LB155',
  LB160 = 'LB160',
  LB163 = 'LB163',
  LB179 = 'LB179',
  LB184 = 'LB184',
  LB187 = 'LB187',
  LB191 = 'LB191',
  LB194 = 'LB194',
  LB197 = 'LB197',
  LB200 = 'LB200',
  LB215 = 'LB215',
  LB217 = 'LB217',
  LB223 = 'LB223',
  LB601 = 'LB601',
  LB603 = 'LB603',
  LB605 = 'LB605',
  LB617 = 'LB617',
  LFI101 = 'LFI101',
  LFI107 = 'LFI107',
  LFI109 = 'LFI109',
  LG101 = 'LG101',
  LG103 = 'LG103',
  LG105 = 'LG105',
  LG109 = 'LG109',
  LG111 = 'LG111',
  LG120 = 'LG120',
  LG148 = 'LG148',
  LG157 = 'LG157',
  LG163 = 'LG163',
  LG166 = 'LG166',
  LG168 = 'LG168',
  LG170 = 'LG170',
  LG173 = 'LG173',
  LG180 = 'LG180',
  LG184 = 'LG184',
  LG189 = 'LG189',
  LG193 = 'LG193',
  LG195 = 'LG195',
  LG197 = 'LG197',
  LG199 = 'LG199',
  LG207 = 'LG207',
  LG217 = 'LG217',
  LG234 = 'LG234',
  LG236 = 'LG236',
  LG239 = 'LG239',
  LG242 = 'LG242',
  LG244 = 'LG244',
  LG245 = 'LG245',
  LG246 = 'LG246',
  LG248 = 'LG248',
  LG252 = 'LG252',
  LG254 = 'LG254',
  LG256 = 'LG256',
  LG270 = 'LG270',
  LG351 = 'LG351',
  LG353 = 'LG353',
  LG359 = 'LG359',
  LG363 = 'LG363',
  LG367 = 'LG367',
  LG374 = 'LG374',
  LG378 = 'LG378',
  LG392 = 'LG392',
  LG400 = 'LG400',
  LG402 = 'LG402',
  LG404 = 'LG404',
  LG426 = 'LG426',
  LG428 = 'LG428',
  LG436 = 'LG436',
  LG450 = 'LG450',
  LG460 = 'LG460',
  LG469 = 'LG469',
  LG479 = 'LG479',
  LG500 = 'LG500',
  LG507 = 'LG507',
  LG520 = 'LG520',
  LG527 = 'LG527',
  LG601 = 'LG601',
  LG603 = 'LG603',
  LG605 = 'LG605',
  LG607 = 'LG607',
  LG609 = 'LG609',
  LG611 = 'LG611',
  LG901 = 'LG901',
  LG904 = 'LG904',
  LGBerlinGerman1st2ndMarineGrenadierDivisionsKriegsmarine = 'LG_berlin_german_1st_2nd_marine_grenadier_divisions_kriegsmarine',
  LGBerlinGermanAufklaerer38TScoutCompany = 'LG_berlin_german_aufklaerer_38_t_scout_company',
  LGBerlinGermanLuchsScoutCompany = 'LG_berlin_german_luchs_scout_company',
  LGBerlinGermanSdKfz234ScoutCompany = 'LG_berlin_german_sd_kfz_234_scout_company',
  LGBerlinGermanSsPanzerbrigadeWestfalenBattleGroup = 'LG_berlin_german_ss_panzerbrigade_westfalen_battle_group',
  LH101 = 'LH101',
  LH103 = 'LH103',
  LH105 = 'LH105',
  LH108 = 'LH108',
  LH112 = 'LH112',
  LH114 = 'LH114',
  LH117 = 'LH117',
  LH119 = 'LH119',
  LR101 = 'LR101',
  LR105 = 'LR105',
  LR107 = 'LR107',
  LR109 = 'LR109',
  LS100 = 'LS100',
  LS103 = 'LS103',
  LS105 = 'LS105',
  LS109 = 'LS109',
  LS118 = 'LS118',
  LS121 = 'LS121',
  LS125 = 'LS125',
  LS128 = 'LS128',
  LS131 = 'LS131',
  LS133 = 'LS133',
  LS152 = 'LS152',
  LS154 = 'LS154',
  LS156 = 'LS156',
  LS159 = 'LS159',
  LS162 = 'LS162',
  LS163 = 'LS163',
  LS166 = 'LS166',
  LS169 = 'LS169',
  LS172 = 'LS172',
  LS175 = 'LS175',
  LS176 = 'LS176',
  LS178 = 'LS178',
  LS180 = 'LS180',
  LS181 = 'LS181',
  LS183 = 'LS183',
  LS191 = 'LS191',
  LS193 = 'LS193',
  LS195 = 'LS195',
  LS197 = 'LS197',
  LS199 = 'LS199',
  LS201 = 'LS201',
  LS210 = 'LS210',
  LS217 = 'LS217',
  LS220 = 'LS220',
  LS226 = 'LS226',
  LS229 = 'LS229',
  LS231 = 'LS231',
  LS601 = 'LS601',
  LS603 = 'LS603',
  LS605 = 'LS605',
  LS607 = 'LS607',
  LS612 = 'LS612',
  LS615 = 'LS615',
  LS619 = 'LS619',
  LU100 = 'LU100',
  LU102 = 'LU102',
  LU104 = 'LU104',
  LU108 = 'LU108',
  LU115 = 'LU115',
  LU125 = 'LU125',
  LU131 = 'LU131',
  LU134 = 'LU134',
  LU137 = 'LU137',
  LU140 = 'LU140',
  LU143 = 'LU143',
  LU146 = 'LU146',
  LU152 = 'LU152',
  LU155 = 'LU155',
  LU156 = 'LU156',
  LU159 = 'LU159',
  LU163 = 'LU163',
  LU165 = 'LU165',
  LU172 = 'LU172',
  LU181 = 'LU181',
  LU187 = 'LU187',
  LU189 = 'LU189',
  LU197 = 'LU197',
  LU199 = 'LU199',
  LU205 = 'LU205',
  LU211 = 'LU211',
  LU216 = 'LU216',
  LU223 = 'LU223',
  LU225 = 'LU225',
  LU237 = 'LU237',
  LU601 = 'LU601',
  LU603 = 'LU603',
  LU605 = 'LU605',
  LU609 = 'LU609',
  LU611 = 'LU611',
  LU613 = 'LU613',
  LU621 = 'LU621',
  MAU101 = 'MAU101',
  MAU111 = 'MAU111',
  Mau201 = 'MAU201',
  Mau221 = 'MAU221',
  Mau225 = 'MAU225',
  Mau601 = 'MAU601',
  MB101 = 'MB101',
  MB103 = 'MB103',
  MB106 = 'MB106',
  MB108 = 'MB108',
  MB120 = 'MB120',
  MB122 = 'MB122',
  MB125 = 'MB125',
  MB128 = 'MB128',
  MB131 = 'MB131',
  MB133 = 'MB133',
  MB201 = 'MB201',
  MB211 = 'MB211',
  MB601 = 'MB601',
  MB602 = 'MB602',
  MB701 = 'MB701',
  MB721 = 'MB721',
  MB731 = 'MB731',
  MB733 = 'MB733',
  MBArmouredFistAustralianDivisionalCavalry = 'MB_armoured_fist_australian_divisional_cavalry',
  MBArmouredFistDaimlerArmouredCarSquadron = 'MB_armoured_fist_daimler_armoured_car_squadron',
  MBArmouredFistMailedFistArmouredCarSquadron = 'MB_armoured_fist_mailed_fist_armoured_car_squadron',
  MBArmouredFistNewZealandDivisionalCavalry = 'MB_armoured_fist_new_zealand_divisional_cavalry',
  MBPacificBritish6thBrigadeVeteranRifleCompany = 'MB_pacific_british_6th_brigade_veteran_rifle_company',
  MBPacificBritishTheChinditsSpecialForceColumn = 'MB_pacific_british_the_chindits_special_force_column',
  MFI101 = 'MFI101',
  MFI107 = 'MFI107',
  MFI111 = 'MFI111',
  MFIWhiteDeathPioneerCompany = 'MFI_white_death_pioneer_company',
  MG101 = 'MG101',
  MG102 = 'MG102',
  MG108 = 'MG108',
  MG112 = 'MG112',
  MG124 = 'MG124',
  MG201 = 'MG201',
  MG203 = 'MG203',
  MG204 = 'MG204',
  MG209 = 'MG209',
  MG215 = 'MG215',
  MG235 = 'MG235',
  MG239 = 'MG239',
  MG241 = 'MG241',
  MG249 = 'MG249',
  MG250 = 'MG250',
  MG301 = 'MG301',
  MGAfrikaKorpsArmouredCarCompany = 'MG_afrika_korps_armoured_car_company',
  MGGhostPanzers189thStugBattery = 'MG_ghost_panzers_189th_stug_battery',
  MGGhostPanzersArmouredCarCompany = 'MG_ghost_panzers_armoured_car_company',
  MGGhostPanzersBrummbaerAssaultTankCompany = 'MG_ghost_panzers_brummbaer_assault_tank_company',
  MGGhostPanzersCapturedT34Company = 'MG_ghost_panzers_captured_t_34_company',
  MGGhostPanzersFerdinandTankHunterCompany = 'MG_ghost_panzers_ferdinand_tank_hunter_company',
  MGGhostPanzersPanzerCompanyRc = 'MG_ghost_panzers_panzer_company_rc',
  MGGhostPanzersReconnaissanceCompany = 'MG_ghost_panzers_reconnaissance_company',
  MGGhostPanzersSsPanzerCompany = 'MG_ghost_panzers_ss_panzer_company',
  MGGhostPanzersStugCompanyRc = 'MG_ghost_panzers_stug_company_rc',
  MGIronCrossArmouredCarCompany = 'MG_iron_cross_armoured_car_company',
  MGIronCrossFastCompany = 'MG_iron_cross_fast_company',
  MGIronCrossStugAssaultGunBattery = 'MG_iron_cross_stug_assault_gun_battery',
  MH101 = 'MH101',
  MH106 = 'MH106',
  MH110 = 'MH110',
  MH114 = 'MH114',
  MH116 = 'MH116',
  MH132 = 'MH132',
  MH601 = 'MH601',
  MH603 = 'MH603',
  MHHungarianSteelMotorisedReconCompany = 'MH_hungarian_steel_motorised_recon_company',
  MI101 = 'MI101',
  MI104 = 'MI104',
  MI107 = 'MI107',
  MI201 = 'MI201',
  MI601 = 'MI601',
  MIAvantiAb41ArmouredCarCompany = 'MI_avanti_ab41_armoured_car_company',
  MIAvantiAssaultEngineerCompany = 'MI_avanti_assault_engineer_company',
  MIAvantiL640LightTankCompany = 'MI_avanti_l6_40_light_tank_company',
  MIAvantiL640ScoutTankCompany = 'MI_avanti_l6_40_scout_tank_company',
  MIAvantiMotorcycleCompany = 'MI_avanti_motorcycle_company',
  MIAvantiParachutistAssaultEngineerCompany = 'MI_avanti_parachutist_assault_engineer_company',
  MJ101 = 'MJ101',
  MJ105 = 'MJ105',
  MJ107 = 'MJ107',
  MJ111 = 'MJ111',
  MJ130 = 'MJ130',
  MJ132 = 'MJ132',
  MJPacificJapanEngineerCompany = 'MJ_pacific_japan_engineer_company',
  MR101 = 'MR101',
  MR103 = 'MR103',
  MR105 = 'MR105',
  MR107 = 'MR107',
  MR115 = 'MR115',
  MR122 = 'MR122',
  MR137 = 'MR137',
  MRBraveRomaniaPioneerCompany = 'MR_brave_romania_pioneer_company',
  MRBraveRomaniaReconnaissanceCompany = 'MR_brave_romania_reconnaissance_company',
  MS100 = 'MS100',
  MS103 = 'MS103',
  MS107 = 'MS107',
  MS110 = 'MS110',
  MS120 = 'MS120',
  MS136 = 'MS136',
  MS140 = 'MS140',
  MS144 = 'MS144',
  MS147 = 'MS147',
  MS149 = 'MS149',
  MS151 = 'MS151',
  MS153 = 'MS153',
  MS600 = 'MS600',
  MS601 = 'MS601',
  MS605 = 'MS605',
  MSEnemyAtTheGatesCossackRegiment = 'MS_enemy_at_the_gates_cossack_regiment',
  MSEnemyAtTheGatesHeroCossackRegiment = 'MS_enemy_at_the_gates_hero_cossack_regiment',
  MSEnemyAtTheGatesMilitiaBattalion = 'MS_enemy_at_the_gates_militia_battalion',
  MSEnemyAtTheGatesNkvdBattalion = 'MS_enemy_at_the_gates_nkvd_battalion',
  MSEnemyAtTheGatesScoutCompany = 'MS_enemy_at_the_gates_scout_company',
  MSRedBannerBa10ArmouredCarCompany = 'MS_red_banner_ba_10_armoured_car_company',
  MSRedBannerMixedSpRegiment = 'MS_red_banner_mixed_sp_regiment',
  MSRedBannerMixedTankBattalionLate = 'MS_red_banner_mixed_tank_battalion_late',
  MSRedBannerSu122MediumSpRegiment = 'MS_red_banner_su_122_medium_sp_regiment',
  MSRedBannerSu152MediumSpRegiment = 'MS_red_banner_su_152_medium_sp_regiment',
  MSRedBannerSu76LightSpRegiment = 'MS_red_banner_su_76_light_sp_regiment',
  MSRedBannerSu85MediumSpRegiment = 'MS_red_banner_su_85_medium_sp_regiment',
  MSRedBannerT70ReconnaissanceTankCompany = 'MS_red_banner_t_70_reconnaissance_tank_company',
  MSRedBannerValentineReconnaissanceTankCompany = 'MS_red_banner_valentine_reconnaissance_tank_company',
  MU101 = 'MU101',
  MU103 = 'MU103',
  MU105 = 'MU105',
  MU111 = 'MU111',
  MU113 = 'MU113',
  MU118 = 'MU118',
  MU131 = 'MU131',
  MU199 = 'MU199',
  MU201 = 'MU201',
  MU301 = 'MU301',
  MU401 = 'MU401',
  MU409 = 'MU409',
  MU411 = 'MU411',
  MU601 = 'MU601',
  MU603 = 'MU603',
  MUFightingFirstAirborneEngineerCombatCompany = 'MU_fighting_first_airborne_engineer_combat_company',
  MUFightingFirstEngineerCombatCompany = 'MU_fighting_first_engineer_combat_company',
  MUFightingFirstM3a1ArmoredReconCompany = 'MU_fighting_first_m3a1_armored_recon_company',
  MUPacificAmericanUsArmyEngineerCombatCompany = 'MU_pacific_american_us_army_engineer_combat_company',
  MUPacificAmericanUsArmyPhilippineRifleCompany = 'MU_pacific_american_us_army_philippine_rifle_company',
  MUPacificAmericanUsMarinesMarineParachuteRifleCompany = 'MU_pacific_american_us_marines_marine_parachute_rifle_company',
  MUPacificAmericanUsMarinesMarineRaiderCompany = 'MU_pacific_american_us_marines_marine_raider_company',
  MUPacificAmericanUsMarinesNavalConstructionCompany = 'MU_pacific_american_us_marines_naval_construction_company',
}

export const units: Record<Unit, UnitMetadata<ForceDiagram>> = {
  [Unit.LB101]: {
    displayName: 'Sherman Armoured Squadron',
    sourceForceDiagram: ForceDiagram.FortressEuropeBritish,
    isFormation: true,
  },
  [Unit.LB104]: {
    displayName: 'Italy Churchill Tank Squadron',
    sourceForceDiagram: ForceDiagram.FortressEuropeBritish,
    isFormation: true,
  },
  [Unit.LB107]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeBritish,
    isFormation: true,
  },
  [Unit.LB110]: {
    displayName: 'Motor Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeBritish,
    isFormation: true,
  },
  [Unit.LB123]: {
    displayName: 'Parachute Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB125]: {
    displayName: 'Airlanding Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB132]: {
    displayName: 'Commando Troop',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB136]: {
    displayName: 'Sherman DD Armoured Squadron',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB140]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB146]: {
    displayName: 'Churchill Armoured Squadron',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB148]: {
    displayName: 'Sherman Armoured Squadron',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB150]: {
    displayName: 'Cromwell Armoured Recce Squadron',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB152]: {
    displayName: 'Motor Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB155]: {
    displayName: 'Desert Rats Cromwell Armoured Squadron',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB160]: {
    displayName: 'Desert Rats Motor Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB163]: {
    displayName: 'Desert Rats Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayBritish,
    isFormation: true,
  },
  [Unit.LB179]: {
    displayName: 'Comet Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB184]: {
    displayName: 'Hussars Cromwell Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB187]: {
    displayName: 'Cromwell Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB191]: {
    displayName: 'Guards Sherman Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB194]: {
    displayName: 'Guards Churchill Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB197]: {
    displayName: 'Black Bull Motor Company',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB200]: {
    displayName: 'Kangaroo Rifle Company',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB215]: {
    displayName: 'Glider Pilot Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB217]: {
    displayName: 'Frost\'s Parachute Company',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB223]: {
    displayName: 'Ram Armoured Squadron',
    sourceForceDiagram: ForceDiagram.BulgeBritish,
    isFormation: true,
  },
  [Unit.LB601]: {
    displayName: 'Tortoise Armoured Squadron',
    sourceForceDiagram: ForceDiagram.LeviathansBritish,
    isFormation: true,
  },
  [Unit.LB603]: {
    displayName: 'Centurion Armoured Squadron',
    sourceForceDiagram: ForceDiagram.LeviathansBritish,
    isFormation: true,
  },
  [Unit.LB605]: {
    displayName: 'Saracen Motor Company',
    sourceForceDiagram: ForceDiagram.LeviathansBritish,
    isFormation: true,
  },
  [Unit.LB617]: {
    displayName: 'Charioteer Armoured Squadron',
    sourceForceDiagram: ForceDiagram.LeviathansBritish,
    isFormation: true,
  },
  [Unit.LFI101]: {
    displayName: 'T-26 Armoured Company',
    sourceForceDiagram: ForceDiagram.BagrationFinnish,
    isFormation: true,
  },
  [Unit.LFI107]: {
    displayName: 'Sturmi Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationFinnish,
    isFormation: true,
  },
  [Unit.LFI109]: {
    displayName: 'Infantry Company',
    sourceForceDiagram: ForceDiagram.BagrationFinnish,
    isFormation: true,
  },
  [Unit.LG101]: {
    displayName: 'Tiger Tank Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG103]: {
    displayName: 'Panther Tank Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG105]: {
    displayName: 'Panzer III & IV Mixed Tank Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG109]: {
    displayName: 'StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG111]: {
    displayName: 'Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG120]: {
    displayName: 'Grenadier Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeGerman,
    isFormation: true,
  },
  [Unit.LG148]: {
    displayName: 'Beach Defence Grenadier Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG157]: {
    displayName: 'Fallschirmjäger Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG163]: {
    displayName: 'Panther Tank Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG166]: {
    displayName: 'Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG168]: {
    displayName: 'Armoured Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG170]: {
    displayName: 'Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG173]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG180]: {
    displayName: 'Tiger Tank Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG184]: {
    displayName: 'Fallschirmjäger StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG189]: {
    displayName: 'Tiger SS Tank Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG193]: {
    displayName: 'Panther SS Tank Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG195]: {
    displayName: 'Panzer IV SS Tank Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG197]: {
    displayName: 'StuG SS Tank Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG199]: {
    displayName: 'Armoured SS Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG207]: {
    displayName: 'SS Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG217]: {
    displayName: 'SS Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.DDayWaffenSs,
    isFormation: true,
  },
  [Unit.LG234]: {
    displayName: 'Grenadier Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG236]: {
    displayName: 'Storm Grenadier Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG239]: {
    displayName: 'StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG242]: {
    displayName: 'Hetzer Tank-Hunter Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG244]: {
    displayName: 'Tiger Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG245]: {
    displayName: 'Panther Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG246]: {
    displayName: 'Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG248]: {
    displayName: 'Panzer IV/70 Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG252]: {
    displayName: 'Armoured Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG254]: {
    displayName: 'Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG256]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.BagrationGerman,
    isFormation: true,
  },
  [Unit.LG270]: {
    displayName: '654. Schwere Panzerjager Jagdpanther Tank-hunter Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG351]: {
    displayName: 'Tiger II Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG353]: {
    displayName: 'Brigade Panther (Late) Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG359]: {
    displayName: 'Panther (Late) Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG363]: {
    displayName: 'Brigade Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG367]: {
    displayName: 'Brigade Armoured Assault Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG374]: {
    displayName: 'Brigade Armoured Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG378]: {
    displayName: 'Brigade Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG392]: {
    displayName: 'Ardennes Armoured Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG400]: {
    displayName: 'Jagdpanther Tank-hunter Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG402]: {
    displayName: 'Jagdtiger Tank-hunter Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG404]: {
    displayName: 'Volksgrenadier Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG426]: {
    displayName: 'Tiger II SS Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG428]: {
    displayName: 'Panther (Late) SS Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG436]: {
    displayName: 'Ardennes Armoured SS Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.BulgeGerman,
    isFormation: true,
  },
  [Unit.LG450]: {
    displayName: 'Berlin Fallschirmjäger Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG460]: {
    displayName: 'Clausewitz Panther (IR) Tank Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG469]: {
    displayName: 'Clausewitz Panzersturm Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG479]: {
    displayName: 'Clausewitz StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG500]: {
    displayName: 'Heavy Tank Training Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG507]: {
    displayName: 'Tank Training Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG520]: {
    displayName: 'Panzer Battle Group',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG527]: {
    displayName: 'Berlin Battle Group',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LG601]: {
    displayName: 'Maus Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG603]: {
    displayName: 'Panther (8.8cm) Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG605]: {
    displayName: 'E-100 Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG607]: {
    displayName: 'Jagdpanzer E-100 Tank-hunter Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG609]: {
    displayName: 'Skorpion Tank-hunter Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG611]: {
    displayName: 'Kätzchen Panzersturm Company',
    sourceForceDiagram: ForceDiagram.LeviathansGerman,
    isFormation: true,
  },
  [Unit.LG901]: {
    displayName: '21st Panzer Hotchkiss Assault Gun Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LG904]: {
    displayName: '21st Panzer Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.DDayGerman,
    isFormation: true,
  },
  [Unit.LGBerlinGerman1st2ndMarineGrenadierDivisionsKriegsmarine]: {
    displayName: '1st & 2nd Marine-Grenadier Divisions Kriegsmarine',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LGBerlinGermanAufklaerer38TScoutCompany]: {
    displayName: 'Aufklärer 38(t) Scout Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LGBerlinGermanLuchsScoutCompany]: {
    displayName: 'Luchs Scout Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LGBerlinGermanSdKfz234ScoutCompany]: {
    displayName: 'Sd Kfz 234 Scout Company',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LGBerlinGermanSsPanzerbrigadeWestfalenBattleGroup]: {
    displayName: 'SS-Panzerbrigade Westfalen Battle Group',
    sourceForceDiagram: ForceDiagram.BerlinGerman,
    isFormation: true,
  },
  [Unit.LH101]: {
    displayName: 'Panther Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH103]: {
    displayName: 'Tiger Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH105]: {
    displayName: 'Turán Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH108]: {
    displayName: 'Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH112]: {
    displayName: 'Zrínyi Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH114]: {
    displayName: 'StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH117]: {
    displayName: 'Hetzer Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LH119]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.BagrationHungarian,
    isFormation: true,
  },
  [Unit.LR101]: {
    displayName: 'R-2 Light Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationRomanian,
    isFormation: true,
  },
  [Unit.LR105]: {
    displayName: 'T-4 Tank Company',
    sourceForceDiagram: ForceDiagram.BagrationRomanian,
    isFormation: true,
  },
  [Unit.LR107]: {
    displayName: 'TA Assault Gun Company',
    sourceForceDiagram: ForceDiagram.BagrationRomanian,
    isFormation: true,
  },
  [Unit.LR109]: {
    displayName: 'Motorised Rifle Company',
    sourceForceDiagram: ForceDiagram.BagrationRomanian,
    isFormation: true,
  },
  [Unit.LS100]: {
    displayName: 'KV-1S Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS103]: {
    displayName: 'Churchill Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS105]: {
    displayName: 'Hero T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS109]: {
    displayName: 'Hero Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS118]: {
    displayName: 'Hero Rifle Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS121]: {
    displayName: 'T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS125]: {
    displayName: 'M3 Lee Tank Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS128]: {
    displayName: 'Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS131]: {
    displayName: 'Rifle Battalion',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS133]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeSoviet,
    isFormation: true,
  },
  [Unit.LS152]: {
    displayName: 'IS-2 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS154]: {
    displayName: 'IS-85 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS156]: {
    displayName: 'Heavy SP Artillery Regiment',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS159]: {
    displayName: 'Medium SP Artillery Regiment',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS162]: {
    displayName: 'Light SP Artillery Regiment',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS163]: {
    displayName: 'Engineer-Sapper Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS166]: {
    displayName: 'Hero Shock Rifle Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS169]: {
    displayName: 'Rifle Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS172]: {
    displayName: 'Hero T-34 (85mm) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS175]: {
    displayName: 'Hero T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS176]: {
    displayName: 'Hero Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS178]: {
    displayName: 'T-34 (85mm) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS180]: {
    displayName: 'T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS181]: {
    displayName: 'Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS183]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.BagrationSoviet,
    isFormation: true,
  },
  [Unit.LS191]: {
    displayName: 'M4 Sherman (Late) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS193]: {
    displayName: 'M4 Sherman (76mm) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS195]: {
    displayName: 'Hero M4 Sherman (Late) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS197]: {
    displayName: 'Hero M4 Sherman (76mm) Tank Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS199]: {
    displayName: 'IS-2 (Late) Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS201]: {
    displayName: 'Red Banner Rifle Regiment',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS210]: {
    displayName: 'Hero Engineer-Sapper Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS217]: {
    displayName: 'Hero IS-2 (Late) Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS220]: {
    displayName: 'Hero Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS226]: {
    displayName: 'Hero Guards Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS229]: {
    displayName: 'M4 Sherman Forward Detachment',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS231]: {
    displayName: 'T-34 Forward Detachment',
    sourceForceDiagram: ForceDiagram.BerlinSoviet,
    isFormation: true,
  },
  [Unit.LS601]: {
    displayName: 'IS-3 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS603]: {
    displayName: 'Heavy SP Artillery Regiment',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS605]: {
    displayName: 'T-44 Tank Battalion',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS607]: {
    displayName: 'Hero BTR Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS612]: {
    displayName: 'T-54-1 Tank Battalion',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS615]: {
    displayName: 'IS-7 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LS619]: {
    displayName: 'T-10 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.LeviathansSoviet,
    isFormation: true,
  },
  [Unit.LU100]: {
    displayName: 'M4 Sherman Tank Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeAmerican,
    isFormation: true,
  },
  [Unit.LU102]: {
    displayName: 'M5 Stuart Tank Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeAmerican,
    isFormation: true,
  },
  [Unit.LU104]: {
    displayName: 'M10 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeAmerican,
    isFormation: true,
  },
  [Unit.LU108]: {
    displayName: 'Armoured Rifle Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeAmerican,
    isFormation: true,
  },
  [Unit.LU115]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.FortressEuropeAmerican,
    isFormation: true,
  },
  [Unit.LU125]: {
    displayName: 'Parachute Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU131]: {
    displayName: 'Glider Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU134]: {
    displayName: 'Ranger Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU137]: {
    displayName: 'Assault Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU140]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU143]: {
    displayName: 'Veteran Assault Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU146]: {
    displayName: 'Veteran Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU152]: {
    displayName: 'M4 Sherman Tank Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU155]: {
    displayName: 'M5 Stuart Tank Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU156]: {
    displayName: 'Armoured Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU159]: {
    displayName: 'M4 Sherman Veteran Tank Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU163]: {
    displayName: 'M5 Stuart Veteran Tank Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU165]: {
    displayName: 'Veteran Armoured Rifle Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU172]: {
    displayName: 'M10 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU181]: {
    displayName: 'M4 Sherman (Late) Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU187]: {
    displayName: 'M24 Chaffee Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU189]: {
    displayName: 'Veteran M4 Sherman (Late) Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU197]: {
    displayName: 'Veteran M24 Chaffee Tank Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU199]: {
    displayName: 'Battle Weary Armoured Rifle Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU205]: {
    displayName: 'Battle Weary Rifle Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU211]: {
    displayName: 'Bastogne Parachute Rifle Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU216]: {
    displayName: 'Bastogne Glider Rifle Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU223]: {
    displayName: 'M36 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU225]: {
    displayName: 'M18 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.BulgeAmerican,
    isFormation: true,
  },
  [Unit.LU237]: {
    displayName: 'M18 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.DDayAmerican,
    isFormation: true,
  },
  [Unit.LU601]: {
    displayName: 'M26 Assault Pershing Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU603]: {
    displayName: 'T28 Assault Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU605]: {
    displayName: 'T29 & T30 Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU609]: {
    displayName: 'M26 Pershing Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU611]: {
    displayName: 'Veteran M4 Easy Eight Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU613]: {
    displayName: 'Leviathan Armoured Rifle Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.LU621]: {
    displayName: 'T34 Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.LeviathansAmerican,
    isFormation: true,
  },
  [Unit.MAU101]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.MAU111]: {
    displayName: 'Commando Independent Company',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.Mau201]: {
    displayName: 'Militia Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.Mau221]: {
    displayName: 'Grant Armoured Squadron',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.Mau225]: {
    displayName: 'Stuart Armoured Squadron',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.Mau601]: {
    displayName: 'Sentinel Armoured Squadron',
    sourceForceDiagram: ForceDiagram.PacificAustralian,
    isFormation: true,
  },
  [Unit.MB101]: {
    displayName: 'Grant Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB103]: {
    displayName: 'Crusader Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB106]: {
    displayName: 'Honey Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB108]: {
    displayName: 'Motor Company',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB120]: {
    displayName: 'Death or Glory Squadron (Valentine)',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB122]: {
    displayName: 'Death or Glory Squadron (Lee)',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB125]: {
    displayName: 'Valentine Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB128]: {
    displayName: 'Churchill Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB131]: {
    displayName: 'Sherman Armoured Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB133]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB201]: {
    displayName: 'Parachute Company',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB211]: {
    displayName: 'Commando Troop',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB601]: {
    displayName: 'T14 Armoured Assault Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB602]: {
    displayName: 'Churchill III Armoured Assault Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MB701]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MB721]: {
    displayName: 'Indian Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MB731]: {
    displayName: 'Honey Armoured Squadron',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MB733]: {
    displayName: 'Grant/Lee Armoured Squadron',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MBArmouredFistAustralianDivisionalCavalry]: {
    displayName: 'Australian Divisional Cavalry',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MBArmouredFistDaimlerArmouredCarSquadron]: {
    displayName: 'Daimler Armoured Car Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MBArmouredFistMailedFistArmouredCarSquadron]: {
    displayName: 'Mailed Fist Armoured Car Squadron',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MBArmouredFistNewZealandDivisionalCavalry]: {
    displayName: 'New Zealand Divisional Cavalry',
    sourceForceDiagram: ForceDiagram.ArmouredFist,
    isFormation: true,
  },
  [Unit.MBPacificBritish6thBrigadeVeteranRifleCompany]: {
    displayName: '6th Brigade Veteran Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MBPacificBritishTheChinditsSpecialForceColumn]: {
    displayName: 'The Chindits Special Force Column',
    sourceForceDiagram: ForceDiagram.PacificBritish,
    isFormation: true,
  },
  [Unit.MFI101]: {
    displayName: 'Armoured Company',
    sourceForceDiagram: ForceDiagram.WhiteDeath,
    isFormation: true,
  },
  [Unit.MFI107]: {
    displayName: 'Infantry Company',
    sourceForceDiagram: ForceDiagram.WhiteDeath,
    isFormation: true,
  },
  [Unit.MFI111]: {
    displayName: 'Light Infantry Company',
    sourceForceDiagram: ForceDiagram.WhiteDeath,
    isFormation: true,
  },
  [Unit.MFIWhiteDeathPioneerCompany]: {
    displayName: 'Pioneer Company',
    sourceForceDiagram: ForceDiagram.WhiteDeath,
    isFormation: true,
  },
  [Unit.MG101]: {
    displayName: 'Panzer III Tank Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MG102]: {
    displayName: 'Panzer III (Uparmoured) Tank Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MG108]: {
    displayName: 'Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MG112]: {
    displayName: 'Africa Rifle Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MG124]: {
    displayName: '90th Light Rifle Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MG201]: {
    displayName: 'Panzer IV Tank Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MG203]: {
    displayName: 'Panzer III Tank Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MG204]: {
    displayName: 'Panzer III (Uparmoured) Tank Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MG209]: {
    displayName: 'Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MG215]: {
    displayName: 'Grenadier Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MG235]: {
    displayName: 'Mixed Panzer Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MG239]: {
    displayName: 'Panther Tank Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MG241]: {
    displayName: 'Armoured Panzergrenadier Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MG249]: {
    displayName: 'Tiger Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MG250]: {
    displayName: 'StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MG301]: {
    displayName: 'Fallschirmjäger Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MGAfrikaKorpsArmouredCarCompany]: {
    displayName: 'Armoured Car Company',
    sourceForceDiagram: ForceDiagram.AfrikaKorps,
    isFormation: true,
  },
  [Unit.MGGhostPanzers189thStugBattery]: {
    displayName: '189th StuG Battery',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersArmouredCarCompany]: {
    displayName: 'Armoured Car Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersBrummbaerAssaultTankCompany]: {
    displayName: 'Brummbär Assault tank Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersCapturedT34Company]: {
    displayName: 'Captured T-34 Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersFerdinandTankHunterCompany]: {
    displayName: 'Ferdinand Tank Hunter Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersPanzerCompanyRc]: {
    displayName: 'Panzer Company (RC)',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersReconnaissanceCompany]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersSsPanzerCompany]: {
    displayName: 'SS-Panzer Company',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGGhostPanzersStugCompanyRc]: {
    displayName: 'StuG Company (RC)',
    sourceForceDiagram: ForceDiagram.GhostPanzers,
    isFormation: true,
  },
  [Unit.MGIronCrossArmouredCarCompany]: {
    displayName: 'Armoured Car Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MGIronCrossFastCompany]: {
    displayName: 'Fast Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MGIronCrossStugAssaultGunBattery]: {
    displayName: 'StuG Assault Gun Company',
    sourceForceDiagram: ForceDiagram.IronCross,
    isFormation: true,
  },
  [Unit.MH101]: {
    displayName: 'T-38 Tank Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH106]: {
    displayName: 'Motorised Rifle Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH110]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH114]: {
    displayName: 'Panzer IV Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH116]: {
    displayName: 'Autocannon Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH132]: {
    displayName: 'Huszár Squadron',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH601]: {
    displayName: 'Turán Tank Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MH603]: {
    displayName: 'Zrínyi Assault Gun Battery',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MHHungarianSteelMotorisedReconCompany]: {
    displayName: 'Motorised Recon Company',
    sourceForceDiagram: ForceDiagram.HungarianSteel,
    isFormation: true,
  },
  [Unit.MI101]: {
    displayName: 'Tank Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MI104]: {
    displayName: 'Bersaglieri Weapons Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MI107]: {
    displayName: 'Bersaglieri Rifle Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MI201]: {
    displayName: 'Parachutist Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MI601]: {
    displayName: 'Heavy Tank Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiAb41ArmouredCarCompany]: {
    displayName: 'AB41 Armoured Car Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiAssaultEngineerCompany]: {
    displayName: 'Assault Engineer Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiL640LightTankCompany]: {
    displayName: 'L6/40 Light Tank Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiL640ScoutTankCompany]: {
    displayName: 'L6/40 Scout Tank Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiMotorcycleCompany]: {
    displayName: 'Motorcycle Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MIAvantiParachutistAssaultEngineerCompany]: {
    displayName: 'Parachutist Assault Engineer Company',
    sourceForceDiagram: ForceDiagram.Avanti,
    isFormation: true,
  },
  [Unit.MJ101]: {
    displayName: 'Type 97 Chi-Ha Tank Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJ105]: {
    displayName: 'Type 89 Chi-Ro Tank Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJ107]: {
    displayName: 'Type 95 Ha-Go Light Tank Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJ111]: {
    displayName: 'Infantry Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJ130]: {
    displayName: 'Type 2 Ka-Mi Naval Tank Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJ132]: {
    displayName: 'Naval Infantry Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MJPacificJapanEngineerCompany]: {
    displayName: 'Engineer Company',
    sourceForceDiagram: ForceDiagram.PacificJapanese,
    isFormation: true,
  },
  [Unit.MR101]: {
    displayName: 'R-2 Light Tank Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR103]: {
    displayName: 'T-3 Medium Tank Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR105]: {
    displayName: 'T-4 Medium Tank Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR107]: {
    displayName: 'Motorised Rifle Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR115]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR122]: {
    displayName: 'Cavalry Squadron',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MR137]: {
    displayName: 'Mountain Rifle Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MRBraveRomaniaPioneerCompany]: {
    displayName: 'Pioneer Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MRBraveRomaniaReconnaissanceCompany]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.BraveRomania,
    isFormation: true,
  },
  [Unit.MS100]: {
    displayName: 'Mixed Tank Battalion',
    sourceForceDiagram: ForceDiagram.EnemyAtTheGates,
    isFormation: true,
  },
  [Unit.MS103]: {
    displayName: 'T-34 (Early) Tank Battalion',
    sourceForceDiagram: ForceDiagram.EnemyAtTheGates,
    isFormation: true,
  },
  [Unit.MS107]: {
    displayName: 'M3 Lee Tank Battalion',
    sourceForceDiagram: ForceDiagram.EnemyAtTheGates,
    isFormation: true,
  },
  [Unit.MS110]: {
    displayName: 'Rifle Battalion',
    sourceForceDiagram: ForceDiagram.EnemyAtTheGates,
    isFormation: true,
  },
  [Unit.MS120]: {
    displayName: 'Hero Rifle Battalion',
    sourceForceDiagram: ForceDiagram.EnemyAtTheGates,
    isFormation: true,
  },
  [Unit.MS136]: {
    displayName: 'T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS140]: {
    displayName: 'Hero T-34 Tank Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS144]: {
    displayName: 'KV-1s Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS147]: {
    displayName: 'Churchill Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS149]: {
    displayName: 'Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS151]: {
    displayName: 'Hero Motor Rifle Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS153]: {
    displayName: 'Reconnaissance Company',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS600]: {
    displayName: 'KV-3 Mixed Tank Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS601]: {
    displayName: 'Hero T-43 Tank Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MS605]: {
    displayName: 'IS-85 Guards Heavy Tank Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSEnemyAtTheGatesCossackRegiment]: {
    displayName: 'Cossack Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSEnemyAtTheGatesHeroCossackRegiment]: {
    displayName: 'Hero Cossack Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSEnemyAtTheGatesMilitiaBattalion]: {
    displayName: 'Militia Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSEnemyAtTheGatesNkvdBattalion]: {
    displayName: 'NKVD Battalion',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSEnemyAtTheGatesScoutCompany]: {
    displayName: 'Scout Company',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerBa10ArmouredCarCompany]: {
    displayName: 'BA-10 Armoured Car Company',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerMixedSpRegiment]: {
    displayName: 'Mixed SP Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerMixedTankBattalionLate]: {
    displayName: 'Mixed Tank Battalion (Late)',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerSu122MediumSpRegiment]: {
    displayName: 'SU-122 Medium SP Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerSu152MediumSpRegiment]: {
    displayName: 'SU-152 Medium SP Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerSu76LightSpRegiment]: {
    displayName: 'SU-76 Light SP Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerSu85MediumSpRegiment]: {
    displayName: 'SU-85 Medium SP Regiment',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerT70ReconnaissanceTankCompany]: {
    displayName: 'T-70 Reconnaissance Tank Company',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MSRedBannerValentineReconnaissanceTankCompany]: {
    displayName: 'Valentine Reconnaissance Tank Company',
    sourceForceDiagram: ForceDiagram.RedBanner,
    isFormation: true,
  },
  [Unit.MU101]: {
    displayName: 'M3 Stuart Tank Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU103]: {
    displayName: 'M3 Lee Tank Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU105]: {
    displayName: 'M4 Sherman Tank Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU111]: {
    displayName: 'M10 Tank Destroyer Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU113]: {
    displayName: 'Armored Rifle Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU118]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU131]: {
    displayName: 'Ranger Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU199]: {
    displayName: 'M3 Stuart Tank Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MU201]: {
    displayName: 'Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MU301]: {
    displayName: 'Parachute Rifle Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU401]: {
    displayName: 'Marine Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MU409]: {
    displayName: 'Marine M3 Stuart Tank Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MU411]: {
    displayName: 'Marine M4 Sherman Tank Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MU601]: {
    displayName: 'M27 Tank Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MU603]: {
    displayName: 'T14 Assault Tank Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MUFightingFirstAirborneEngineerCombatCompany]: {
    displayName: 'Airborne Engineer Combat Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MUFightingFirstEngineerCombatCompany]: {
    displayName: 'Engineer Combat Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MUFightingFirstM3a1ArmoredReconCompany]: {
    displayName: 'M3AI Armored Recon Company',
    sourceForceDiagram: ForceDiagram.FightingFirst,
    isFormation: true,
  },
  [Unit.MUPacificAmericanUsArmyEngineerCombatCompany]: {
    displayName: 'US Army Engineer Combat Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MUPacificAmericanUsArmyPhilippineRifleCompany]: {
    displayName: 'US Army Philippine Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MUPacificAmericanUsMarinesMarineParachuteRifleCompany]: {
    displayName: 'US Marines Marine Parachute Rifle Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MUPacificAmericanUsMarinesMarineRaiderCompany]: {
    displayName: 'US Marines Marine Raider Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
  [Unit.MUPacificAmericanUsMarinesNavalConstructionCompany]: {
    displayName: 'US Marines Naval Construction Company',
    sourceForceDiagram: ForceDiagram.PacificAmerican,
    isFormation: true,
  },
} as const;

export const getUnitOptions = () => getOptions(units);

export const getUnitDisplayName = (
  key: Unit,
) => getDisplayName(units, key);
