import { FactionMetadata } from '../types';
import { Alignment } from './alignments';

export enum Faction {
  Australia = 'australia',
  Belgium = 'belgium',
  Bulgaria = 'bulgaria',
  Canada = 'canada',
  EastAfrica = 'east_africa',
  Finland = 'finland',
  France = 'france',
  Germany = 'germany',
  GreatBritain = 'great_britain',
  Greece = 'greece',
  Hungary = 'hungary',
  ImperialJapan = 'imperial_japan',
  India = 'india',
  Italy = 'italy',
  Netherlands = 'netherlands',
  NewZealand = 'new_zealand',
  Norway = 'norway',
  Partisans = 'partisans',
  Poland = 'poland',
  PolishPeoplesArmy = 'polish_peoples_army',
  Romania = 'romania',
  SouthAfrica = 'south_africa',
  SovietUnion = 'soviet_union',
  UnitedStates = 'united_states',
}

export const factions: Record<Faction, FactionMetadata<Alignment>> = {
  [Faction.Australia]: {
    displayName: 'Australia',
    displayAdjective: 'Australian',
    displayPlural: 'Australians',
    alignment: Alignment.Allies,
  },
  [Faction.Belgium]: {
    displayName: 'Belgium',
    displayAdjective: 'Belgian',
    displayPlural: 'Belgians',
    alignment: Alignment.Allies,
  },
  [Faction.Bulgaria]: {
    displayName: 'Bulgaria',
    displayAdjective: 'Bulgarian',
    displayPlural: 'Bulgarians',
    alignment: Alignment.Flexible,
  },
  [Faction.Canada]: {
    displayName: 'Canada',
    displayAdjective: 'Canadian',
    displayPlural: 'Canadians',
    alignment: Alignment.Allies,
  },
  [Faction.EastAfrica]: {
    displayName: 'East Africa',
    displayAdjective: 'East African',
    displayPlural: 'East Africans',
    alignment: Alignment.Allies,
  },
  [Faction.Finland]: {
    displayName: 'Finland',
    displayAdjective: 'Finnish',
    displayPlural: 'Finns',
    alignment: Alignment.Flexible,
  },
  [Faction.France]: {
    displayName: 'France',
    displayAdjective: 'French',
    displayPlural: 'French',
    alignment: Alignment.Allies,
  },
  [Faction.Germany]: {
    displayName: 'Germany',
    displayAdjective: 'German',
    displayPlural: 'Germans',
    alignment: Alignment.Axis,
  },
  [Faction.GreatBritain]: {
    displayName: 'Great Britain',
    displayAdjective: 'British',
    displayPlural: 'British',
    alignment: Alignment.Allies,
  },
  [Faction.Greece]: {
    displayName: 'Greece',
    displayAdjective: 'Greek',
    displayPlural: 'Greeks',
    alignment: Alignment.Allies,
  },
  [Faction.Hungary]: {
    displayName: 'Hungary',
    displayAdjective: 'Hungarian',
    displayPlural: 'Hungarians',
    alignment: Alignment.Axis,
  },
  [Faction.ImperialJapan]: {
    displayName: 'Imperial Japan',
    displayAdjective: 'Japanese',
    displayPlural: 'Japanese',
    alignment: Alignment.Axis,
  },
  [Faction.India]: {
    displayName: 'India',
    displayAdjective: 'Indian',
    displayPlural: 'Indians',
    alignment: Alignment.Allies,
  },
  [Faction.Italy]: {
    displayName: 'Italy',
    displayAdjective: 'Italian',
    displayPlural: 'Italians',
    alignment: Alignment.Flexible,
  },
  [Faction.Netherlands]: {
    displayName: 'The Netherlands',
    displayAdjective: 'Dutch',
    displayPlural: 'Dutch',
    alignment: Alignment.Allies,
  },
  [Faction.NewZealand]: {
    displayName: 'New Zealand',
    displayAdjective: 'New Zealand',
    displayPlural: 'New Zealanders',
    alignment: Alignment.Allies,
  },
  [Faction.Norway]: {
    displayName: 'Norway',
    displayAdjective: 'Norwegian',
    displayPlural: 'Norwegians',
    alignment: Alignment.Allies,
  },
  [Faction.Partisans]: {
    displayName: 'Partisans', // Yugoslavia
    displayAdjective: 'Partisan',
    displayPlural: 'Partisans',
    alignment: Alignment.Allies,
  },
  [Faction.Poland]: {
    displayName: 'Poland',
    displayAdjective: 'Polish',
    displayPlural: 'Poles',
    alignment: Alignment.Allies,
  },
  [Faction.PolishPeoplesArmy]: {
    displayName: 'Polish People’s Army (LWP)',
    displayAdjective: 'Polish People’s Army',
    displayPlural: 'Polish People’s Army',
    alignment: Alignment.Allies,
  },
  [Faction.Romania]: {
    displayName: 'Romania',
    displayAdjective: 'Romanian',
    displayPlural: 'Romanians',
    alignment: Alignment.Flexible,
  },
  [Faction.SouthAfrica]: {
    displayName: 'South Africa',
    displayAdjective: 'South African',
    displayPlural: 'South Africans',
    alignment: Alignment.Allies,
  },
  [Faction.SovietUnion]: {
    displayName: 'Soviet Union',
    displayAdjective: 'Soviet',
    displayPlural: 'Soviets',
    alignment: Alignment.Allies,
  },
  [Faction.UnitedStates]: {
    displayName: 'United States',
    displayAdjective: 'American',
    displayPlural: 'Americans',
    alignment: Alignment.Allies,
  },
} as const;
